/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html',
  './src/App.jsx',
  './src/main.jsx',
  './src/index.css',
  './src/components/Sidebar.jsx',
  './src/components/OptionsBar.jsx',
  './src/components/Profile.jsx',
  './src/components/ChatWindow.jsx',
  './src/components/buttons/SearchButton.jsx',
  './src/components/ChatRooms.jsx',
  './src/components/buttons/Buttons.jsx',
  './src/components/buttons/PhotoCircleButtons.jsx',
  './src/components/sub-components/ChatRooms.jsx',
  './src/components/sub-components/ChatWindowMessages.jsx',
  './src/pages/AuthPage.jsx',
  './src/components/LoginSide.jsx',
  './src/components/RegistrationSide.jsx',
  './src/components/Layout.jsx',
  './src/pages/FriendsPage.jsx',
  './src/components/Forms/RegistrationForm.jsx',
  './src/components/Forms/LoginForm.jsx',
  './src/components/popups/AddFriendPopUp.jsx',
  './src/components/popups/ConfirmDeletePopup.jsx',
  './src/components/popups/StartNewChatPopup.jsx',
  './src/pages/SingleChat.jsx',
  './src/pages/ChatPage.jsx',
  './src/components/sub-components/ContactsProfile.jsx',
  './src/Modules/Friends Module/components/FriendsSide.jsx',
  './src/Modules/Chat Module/components/ChatSide.jsx',
  './src/Modules/Chat Module/subComponents/MessageChat.jsx',
  './src/Modules/Auth Module/components/AuthError.jsx',
  './src/Modules/Auth Module/components/ChosenAuth.jsx',
  './src/Modules/Auth Module/components/SelectAuth.jsx',
  './src/Modules/Auth Module/Forms/LoginForm.jsx',
  './src/Modules/Auth Module/Forms/RegistrationForm.jsx',
  './src/Modules/Auth Module/subComponents/LoginSide.jsx',
  './src/Modules/Auth Module/subComponents/RegistrationSide.jsx',
],
darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'dark-gray': '#1C1C1C',
        'side-dark': '#2e2e2e',
        'chat-dark': '#262626'
      },
      animation: {
        spin: 'spin 2s linear infinite',
      },
    },
  },
  plugins: [],
}
